spring:
  application:
    name: springboot-graalvm-lambda

# R2DBC Configuration for Reactive Database Access
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/productdb
    username: postgres
    password: password
    pool:
      initial-size: 20
      max-size: 50
      max-idle-time: 30m
      max-acquire-time: 10s
      max-create-connection-time: 5s
      validation-query: SELECT 1
  
# Data Initialization (R2DBC)
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  


# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

