apiVersion: v1
kind: Service
metadata:
  name: springboot-graalvm-service-jit
spec:
  type: NodePort
  selector:
    app: springboot-graalvm-jit
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002