apiVersion: v1
kind: Service
metadata:
  name: springboot-graalvm-service
spec:
  type: NodePort
  selector:
    app: springboot-graalvm
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080