global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'springboot-graalvm'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['springboot-graalvm-jit:8080', 'springboot-graalvm-aot:8080']
